/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_C_PIXI_BUILD_BACKEND__
#define __RUST_C_PIXI_BUILD_BACKEND__
#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \brief
 *  A `struct` usable from both Rust and C
 */
/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef
#endif
enum Platform {
    /** <No documentation available> */
    PLATFORM_NO_ARCH,
    /** <No documentation available> */
    PLATFORM_UNKNOWN,
    /** <No documentation available> */
    PLATFORM_LINUX32,
    /** <No documentation available> */
    PLATFORM_LINUX64,
    /** <No documentation available> */
    PLATFORM_LINUX_AARCH64,
    /** <No documentation available> */
    PLATFORM_LINUX_ARM_V6L,
    /** <No documentation available> */
    PLATFORM_LINUX_ARM_V7L,
    /** <No documentation available> */
    PLATFORM_LINUX_LOONG64,
    /** <No documentation available> */
    PLATFORM_LINUX_PPC64LE,
    /** <No documentation available> */
    PLATFORM_LINUX_PPC64,
    /** <No documentation available> */
    PLATFORM_LINUX_PPC,
    /** <No documentation available> */
    PLATFORM_LINUX_S390_X,
    /** <No documentation available> */
    PLATFORM_LINUX_RISCV32,
    /** <No documentation available> */
    PLATFORM_LINUX_RISCV64,
    /** <No documentation available> */
    PLATFORM_OSX64,
    /** <No documentation available> */
    PLATFORM_OSX_ARM64,
    /** <No documentation available> */
    PLATFORM_WIN32,
    /** <No documentation available> */
    PLATFORM_WIN64,
    /** <No documentation available> */
    PLATFORM_WIN_ARM64,
    /** <No documentation available> */
    PLATFORM_EMSCRIPTEN_WASM32,
    /** <No documentation available> */
    PLATFORM_WASI_WASM32,
    /** <No documentation available> */
    PLATFORM_ZOS_Z,
}
#ifndef DOXYGEN
; typedef uint8_t
#endif
Platform_t;

/** <No documentation available> */
Platform_t
ppb_platform_current (void);


#include <stdbool.h>

/** <No documentation available> */
bool
ppb_platform_is_linux (
    Platform_t const * p);

/** <No documentation available> */
bool
ppb_platform_is_osx (
    Platform_t const * p);

/** <No documentation available> */
bool
ppb_platform_is_unix (
    Platform_t const * p);

/** <No documentation available> */
bool
ppb_platform_is_windows (
    Platform_t const * p);

/** \brief
 *  Don't forget to free returned value.
 */
char *
ppb_platform_name (
    Platform_t const * p);

/** <No documentation available> */
char *
ppb_platform_only_platform (
    Platform_t const * p);


#ifdef __cplusplus
} /* extern \"C\" */
#endif

#endif /* __RUST_C_PIXI_BUILD_BACKEND__ */
